Build with gcc 10
* Add CI job for gcc 10
* Add missing header
* Add workaround for warning -Wtype-limits in membank_base when
  StartAddr is 0 using std::greater/less_equal.
  error: comparison is always true due to limited range of data type
  [-Werror=type-limits]